import type { TabType, TabVisibilityConfig } from './types';

export const TAB_ICONS: Record<TabType, string> = {
  profile: 'i-ph:user-circle-fill',
  settings: 'i-ph:gear-six-fill',
  notifications: 'i-ph:bell-fill',
  features: 'i-ph:star-fill',
  data: 'i-ph:database-fill',
  'cloud-providers': 'i-ph:cloud-fill',
  'local-providers': 'i-ph:desktop-fill',
  'service-status': 'i-ph:activity-bold',
  connection: 'i-ph:wifi-high-fill',
  debug: 'i-ph:bug-fill',
  'event-logs': 'i-ph:list-bullets-fill',
  update: 'i-ph:arrow-clockwise-fill',
  'task-manager': 'i-ph:chart-line-fill',
  'tab-management': 'i-ph:squares-four-fill',
  credits: 'i-ph:coins-fill',
  about: 'i-ph:robot',
  general: 'i-ph:gear',
  appearance: 'i-ph:paint-brush',
  advanced: 'i-ph:sliders',
};

export const TAB_LABELS: Record<TabType, string> = {
  profile: 'Profile',
  settings: 'Settings',
  notifications: 'Notifications',
  features: 'Features',
  data: 'Data Management',
  'cloud-providers': 'Cloud Providers',
  'local-providers': 'Local Providers',
  'service-status': 'Service Status',
  connection: 'Connection',
  debug: 'Debug',
  'event-logs': 'Event Logs',
  update: 'Updates',
  'task-manager': 'Task Manager',
  'tab-management': 'Tab Management',
  credits: 'Credits',
  about: 'About our AI',
  general: 'General',
  appearance: 'Appearance',
  advanced: 'Advanced',
};

export const TAB_DESCRIPTIONS: Record<TabType, string> = {
  profile: 'Manage your profile and account settings',
  settings: 'Configure application preferences',
  notifications: 'View and manage your notifications',
  features: 'Explore new and upcoming features',
  data: 'Manage your data and storage',
  'cloud-providers': 'Configure cloud AI providers and models',
  'local-providers': 'Configure local AI providers and models',
  'service-status': 'Monitor cloud LLM service status',
  connection: 'Check connection status and settings',
  debug: 'Debug tools and system information',
  'event-logs': 'View system events and logs',
  update: 'Check for updates and release notes',
  'task-manager': 'Monitor system resources and processes',
  'tab-management': 'Configure visible tabs and their order',
  credits: 'Manage your credits and usage history',
  about: 'Learn about our AI Software Engineer and its capabilities',
  general: 'General settings and preferences',
  appearance: 'Customize the look and feel',
  advanced: 'Advanced configuration options',
};

export const DEFAULT_TAB_CONFIG: TabVisibilityConfig[] = [
  {
    id: 'profile',
    visible: true,
    window: 'user',
    order: 0,
  },
  {
    id: 'settings',
    visible: true,
    window: 'user',
    order: 1,
  },
  {
    id: 'notifications',
    visible: true,
    window: 'user',
    order: 2,
  },
  {
    id: 'features',
    visible: true,
    window: 'user',
    order: 3,
  },
  {
    id: 'data',
    visible: true,
    window: 'user',
    order: 4,
  },
  {
    id: 'credits',
    visible: true,
    window: 'user',
    order: 5,
  },
  {
    id: 'about',
    visible: true,
    window: 'user',
    order: 6,
  },
  {
    id: 'cloud-providers',
    visible: true,
    window: 'developer',
    order: 0,
  },
  {
    id: 'local-providers',
    visible: true,
    window: 'developer',
    order: 1,
  },
  {
    id: 'service-status',
    visible: true,
    window: 'developer',
    order: 2,
  },
  {
    id: 'connection',
    visible: true,
    window: 'developer',
    order: 3,
  },
  {
    id: 'debug',
    visible: true,
    window: 'developer',
    order: 4,
  },
  {
    id: 'event-logs',
    visible: true,
    window: 'developer',
    order: 5,
  },
  {
    id: 'update',
    visible: true,
    window: 'developer',
    order: 6,
  },
  {
    id: 'task-manager',
    visible: true,
    window: 'developer',
    order: 7,
  },
];
